#!/bin/sh /etc/rc.common
# Copyright (C) 2021 ruoshan
 
START=17
STOP=89
USE_PROCD=1
 

start_service() {
        procd_open_instance
        procd_set_param command http2-proxy-redir -l ":1086"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
        procd_close_instance
}
