name: CI

on:
  push:
    branches:
      - main
    tags:
      - v.*
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  release:
    if: ${{ startsWith(github.ref, "refs/tags") }}
    runs-on: ubuntu-latest
    steps:
      - name: Build for x64 linux
        run: go build --ldflags "-s" .
        
      - name: Release binary
        uses: softprops/action-gh-release@0.1.5
        with:
          files: http2-proxy-redir
          name: latest-${{ github.sha }}
