name: CI

on:
  push:
    branches:
      - main
  create:
    tags:
      - v.*
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Build for x64 linux
      run: go build --ldflags "-s" -o http2-proxy-redir-x64 .

    - name: Build for mipsle (softfloat) (for SoC like MT7621)
      run: GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build --ldflags "-s" -o http2-proxy-redir-mipsle
      
    - name: Release binary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          http2-proxy-redir-x64
          http2-proxy-redir-mipsle
        name: ${{ steps.get_version.outputs.version }}
